language: elixir

sudo: false

elixir:
  - 1.9

otp_release:
  - 22.2

cache:
  directories:
    - _build
    - deps

env: MIX_ENV=test

services:
  - postgresql

before_install:
  - cp config/secrets.exs.example config/secrets.exs
  - cp config/test_secrets.exs.example config/test_secrets.exs

before_script:
  - mix ecto.create
  - mix ecto.migrate

script:
  - mix coveralls.travis
  - mix credo
  - mix format --check-formatted
